import type { Metadata } from "next";
import "./globals.css";
import ClientProviders from "@/features/shared/client-provider";
import { Sidebar } from "@/features/shared/sidebar";
import localFont from "next/font/local";


const montserrat = localFont({
  src: "./fonts/Montserrat-VariableFont_wght.ttf",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${montserrat.className} antialiased`}>
        <ClientProviders>
          <div className="">
            {/* SOL SABİT SIDEBAR */}
            <Sidebar />

            {/* SAĞ İÇERİK ALANI */}
            <main className="">{children}</main>
          </div>
        </ClientProviders>
      </body>
    </html>
  );
}
