import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProviders from "@/features/shared/client-provider";
import { Sidebar } from "@/features/shared/sidebar";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientProviders>
          <div className="">
            {/* SOL SABİT SIDEBAR */}
            <Sidebar />

            {/* SAĞ İÇERİK ALANI */}
            <main className="">{children}</main>
          </div>
        </ClientProviders>
      </body>
    </html>
  );
}
